// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct Account: Codable {
    public let id: String
    public let name: String
    public let balance: Double
    public let moneyBalance: Double
    public let pointBalance: Double
    public let pointDebt: Double
    public let isSuspended: Bool
    public let status: String
    public let privateMoney: PrivateMoney

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case name = "name"
        case balance = "balance"
        case moneyBalance = "money_balance"
        case pointBalance = "point_balance"
        case pointDebt = "point_debt"
        case isSuspended = "is_suspended"
        case status = "status"
        case privateMoney = "private_money"
    }
}
