// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct AccountCampaignPointAmounts: Codable {
    public let maxTotalPointAmount: Int;
    public let totalPointAmount: Int;
    public let remainPointAmount: Int;

    private enum CodingKeys: String, CodingKeys {
        case maxTotalPointAmount = "max_total_point_amount"
        case totalPointAmount = "total_point_amount"
        case remainPointAmount = "remain_point_amount"
    }
}
