// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct AccountTopupStats: Codable {
    public let currentAmount: Int;
    public let limitAmount: Int;
    public let remainingAmount: Int;
    public let startedAt: String;

    private enum CodingKeys: String, CodingKey {
        case currentAmount = "current_amount"
        case limitAmount = "limit_amount"
        case remainingAmount = "remaining_amount"
        case startedAt = "started_at"
    }
}
