// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct Account: Codable {
    public let id: String;
    public let name: String;
    public let balance: Int;
    public let moneyBalance: Int;
    public let pointBalance: Int;
    public let pointDebt: Int;
    public let isSuspended: Bool;
    public let privateMoney: PrivateMoney;

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case name = "name"
        case balance = "balance"
        case moneyBalance = "money_balance"
        case pointBalance = "point_balance"
        case pointDebt = "point_debt"
        case isSuspended = "is_suspended"
        case privateMoney = "private_money"
    }
}
