// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct BillWithAdditionalPrivateMoneys: Codable {
    public let id: String;
    public let amount: Int;
    public let description: String;
    public let user: User;
    public let isOnetime: Bool;
    public let isDisabled: Bool;
    public let privateMoney: PrivateMoney;
    public let token: String;
    public let maxAmount: Int;
    public let minAmount: Int;
    public let additionalPrivateMoneys: [PrivateMoney];

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case amount = "amount"
        case description = "description"
        case user = "user"
        case isOnetime = "is_onetime"
        case isDisabled = "is_disabled"
        case privateMoney = "private_money"
        case token = "token"
        case maxAmount = "max_amount"
        case minAmount = "min_amount"
        case additionalPrivateMoneys = "additional_private_moneys"
    }
}
