// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct CashtrayAttempt: Codable {
    public let user: User?
    public let account: Account?
    public let statusCode: Double
    public let errorType: String
    public let errorMessage: String
    public let createdAt: String
    public let strategy: String?

    private enum CodingKeys: String, CodingKey {
        case user = "user"
        case account = "account"
        case statusCode = "status_code"
        case errorType = "error_type"
        case errorMessage = "error_message"
        case createdAt = "created_at"
        case strategy = "strategy"
    }
}
