// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct CashtrayWithAttemptAndTransaction: Codable {
    public let id: String
    public let amount: Double
    public let description: String
    public let user: User
    public let privateMoney: PrivateMoney
    public let expiresAt: String
    public let canceledAt: String?
    public let token: String
    public let attempt: CashtrayAttempt?
    public let transaction: UserTransaction?

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case amount = "amount"
        case description = "description"
        case user = "user"
        case privateMoney = "private_money"
        case expiresAt = "expires_at"
        case canceledAt = "canceled_at"
        case token = "token"
        case attempt = "attempt"
        case transaction = "transaction"
    }
}
