// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct CashtrayAttempts: Codable {
    public let rows: [CashtrayAttempt];

    private enum CodingKeys: String, CodingKeys {
        case rows = "rows"
    }
}
