// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct Cashtray: Codable {
    public let id: String;
    public let amount: Int;
    public let description: String;
    public let user: User;
    public let privateMoney: PrivateMoney;
    public let expiresAt: String;
    public let canceledAt: String;
    public let token: String;

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case amount = "amount"
        case description = "description"
        case user = "user"
        case privateMoney = "private_money"
        case expiresAt = "expires_at"
        case canceledAt = "canceled_at"
        case token = "token"
    }
}
