// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct Check: Codable {
    public let id: String
    public let amount: Double
    public let moneyAmount: Double
    public let pointAmount: Double
    public let description: String
    public let user: User
    public let isOnetime: Bool
    public let isDisabled: Bool
    public let expiresAt: String
    public let pointExpiresAt: String?
    public let pointExpiresInDays: Int?
    public let privateMoney: PrivateMoney
    public let token: String

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case amount = "amount"
        case moneyAmount = "money_amount"
        case pointAmount = "point_amount"
        case description = "description"
        case user = "user"
        case isOnetime = "is_onetime"
        case isDisabled = "is_disabled"
        case expiresAt = "expires_at"
        case pointExpiresAt = "point_expires_at"
        case pointExpiresInDays = "point_expires_in_days"
        case privateMoney = "private_money"
        case token = "token"
    }
}
