// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct CpmToken: Codable {
    public let cpmToken: String;
    public let account: Account;
    public let transaction: UserTransaction;
    public let scopes: [String];
    public let expiresAt: String;
    public let metadata: String;

    private enum CodingKeys: String, CodingKeys {
        case cpmToken = "cpm_token"
        case account = "account"
        case transaction = "transaction"
        case scopes = "scopes"
        case expiresAt = "expires_at"
        case metadata = "metadata"
    }
}
