// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct CpmToken: Codable {
    public let cpmToken: String
    public let account: Account
    public let transaction: UserTransactionWithTransfers?
    public let scopes: [String]
    public let expiresAt: String
    public let metadata: Object
    public let strategy: String?
    public let couponId: String?

    private enum CodingKeys: String, CodingKey {
        case cpmToken = "cpm_token"
        case account = "account"
        case transaction = "transaction"
        case scopes = "scopes"
        case expiresAt = "expires_at"
        case metadata = "metadata"
        case strategy = "strategy"
        case couponId = "coupon_id"
    }
}
