// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct DetailedShopInformation: Codable {
    public let id: String
    public let name: String
    public let tags: [UserTagInformation]
    public let businessHours: String
    public let regularClosedDays: String
    public let url: String?
    public let logoImageUrl: String?
    public let imageUrls: [String]
    public let address: String?
    public let tel: String?

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case name = "name"
        case tags = "tags"
        case businessHours = "business_hours"
        case regularClosedDays = "regular_closed_days"
        case url = "url"
        case logoImageUrl = "logo_image_url"
        case imageUrls = "image_urls"
        case address = "address"
        case tel = "tel"
    }
}
