// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct IdentificationResult: Codable {
    public let isValid: Bool;
    public let identifiedAt: String;
    public let match: Object;

    private enum CodingKeys: String, CodingKeys {
        case isValid = "is_valid"
        case identifiedAt = "identified_at"
        case match = "match"
    }
}
