// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct JihanpiTransaction: Codable {
    public let orderId: String
    public let transaction: UserTransactionWithTransfers?
    public let account: Account
    public let vendingMachineInfo: JihanpiVendingMachine
    public let state: String
    public let errorReason: String?
    public let strategy: String

    private enum CodingKeys: String, CodingKey {
        case orderId = "order_id"
        case transaction = "transaction"
        case account = "account"
        case vendingMachineInfo = "vending_machine_info"
        case state = "state"
        case errorReason = "error_reason"
        case strategy = "strategy"
    }
}
