// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct JihanpiVendingMachine: Codable {
    public let nfcTagId: String
    public let shopId: String
    public let shopName: String

    private enum CodingKeys: String, CodingKey {
        case nfcTagId = "nfc_tag_id"
        case shopId = "shop_id"
        case shopName = "shop_name"
    }
}
