// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct OauthFullAccessUrl: Codable {
    public let url: String

    private enum CodingKeys: String, CodingKey {
        case url = "url"
    }
}
