// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct Organization: Codable {
    public let code: String;
    public let name: String;

    private enum CodingKeys: String, CodingKeys {
        case code = "code"
        case name = "name"
    }
}
