// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct PaginatedCVSAuthorizations: Codable {
    public let perPage: Int
    public let count: Int
    public let next: String?
    public let prev: String?
    public let items: [CVSAuthorization]

    private enum CodingKeys: String, CodingKey {
        case perPage = "per_page"
        case count = "count"
        case next = "next"
        case prev = "prev"
        case items = "items"
    }
}
