// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct PaginatedAccountTopupStats: Codable {
    public let rows: [AccountTopupStats]

    private enum CodingKeys: String, CodingKey {
        case rows = "rows"
    }
}
