// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct PrivateMoneyLegalText: Codable {
    public let text: String

    private enum CodingKeys: String, CodingKey {
        case text = "text"
    }
}
