// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct PrivateMoney: Codable {
    public let id: String;
    public let name: String;
    public let type: String;
    public let unit: String;
    public let description: String;
    public let onelineMessage: String;
    public let displayMoneyAndPoint: String;
    public let accountImage: String;
    public let images: PrivateMoneyImages;
    public let organization: Organization;
    public let maxBalance: Int;
    public let transferLimit: Int;
    public let expirationType: String;
    public let isExclusive: Bool;
    public let termsUrl: String;
    public let privacyPolicyUrl: String;
    public let paymentActUrl: String;
    public let commercialActUrl: String;

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case name = "name"
        case type = "type"
        case unit = "unit"
        case description = "description"
        case onelineMessage = "oneline_message"
        case displayMoneyAndPoint = "display_money_and_point"
        case accountImage = "account_image"
        case images = "images"
        case organization = "organization"
        case maxBalance = "max_balance"
        case transferLimit = "transfer_limit"
        case expirationType = "expiration_type"
        case isExclusive = "is_exclusive"
        case termsUrl = "terms_url"
        case privacyPolicyUrl = "privacy_policy_url"
        case paymentActUrl = "payment_act_url"
        case commercialActUrl = "commercial_act_url"
    }
}
