// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct PrivateMoneyTopupMethod: Codable {
    public let type: String
    public let name: String
    public let amounts: [Double]?
    public let range: [Double]?

    private enum CodingKeys: String, CodingKey {
        case type = "type"
        case name = "name"
        case amounts = "amounts"
        case range = "range"
    }
}
