// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct Product: Codable {
    public let janCode: String;
    public let name: String;
    public let unitPrice: Int;
    public let price: Int;
    public let quantity: Int;
    public let isDiscounted: Bool;
    public let other: String;

    private enum CodingKeys: String, CodingKeys {
        case janCode = "jan_code"
        case name = "name"
        case unitPrice = "unit_price"
        case price = "price"
        case quantity = "quantity"
        case isDiscounted = "is_discounted"
        case other = "other"
    }
}
