// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct SevenBankAtmSession: Codable {
    public let qrInfo: String;
    public let account: Account;
    public let amount: Int;
    public let transaction: UserTransactionWithTransfers;

    private enum CodingKeys: String, CodingKeys {
        case qrInfo = "qr_info"
        case account = "account"
        case amount = "amount"
        case transaction = "transaction"
    }
}
