// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct ShopInformation: Codable {
    public let id: String
    public let name: String
    public let tags: [UserTagInformation]
    public let logoImageUrl: String?

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case name = "name"
        case tags = "tags"
        case logoImageUrl = "logo_image_url"
    }
}
