// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct Terminal: Codable {
    public let id: String;
    public let name: String;
    public let hardwareId: String;
    public let pushService: String;
    public let pushToken: String;
    public let user: UserWithDetails;
    public let account: Nil;

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case name = "name"
        case hardwareId = "hardware_id"
        case pushService = "push_service"
        case pushToken = "push_token"
        case user = "user"
        case account = "account"
    }
}
