// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct UserTagGroup: Codable {
    public let groupName: String
    public let id: String

    private enum CodingKeys: String, CodingKey {
        case groupName = "group_name"
        case id = "id"
    }
}
