// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct UserTagGroupItem: Codable {
    public let itemName: String
    public let id: String

    private enum CodingKeys: String, CodingKey {
        case itemName = "item_name"
        case id = "id"
    }
}
