// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct User: Codable {
    public let id: String;
    public let name: String;
    public let isMerchant: Bool;

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case name = "name"
        case isMerchant = "is_merchant"
    }
}
