// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct UserBank: Codable {
    public let id: String;
    public let privateMoney: PrivateMoney;
    public let bankName: String;
    public let bankCode: String;
    public let branchNumber: String;
    public let branchName: String;
    public let depositType: String;
    public let maskedAccountNumber: String;
    public let accountName: String;

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case privateMoney = "private_money"
        case bankName = "bank_name"
        case bankCode = "bank_code"
        case branchNumber = "branch_number"
        case branchName = "branch_name"
        case depositType = "deposit_type"
        case maskedAccountNumber = "masked_account_number"
        case accountName = "account_name"
    }
}
