// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct UserTransactionWithTransfersAndCustomerBalance: Codable {
    public let id: String
    public let user: User
    public let balance: Double
    public let customerBalance: Double
    public let amount: Double
    public let moneyAmount: Double
    public let pointAmount: Double
    public let rawPointAmount: Double?
    public let campaignPointAmount: Double?
    public let account: Account
    public let description: String
    public let doneAt: String
    public let type: String
    public let isModified: Bool
    public let transfers: [UserTransferWithoutAccount]

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case user = "user"
        case balance = "balance"
        case customerBalance = "customer_balance"
        case amount = "amount"
        case moneyAmount = "money_amount"
        case pointAmount = "point_amount"
        case rawPointAmount = "raw_point_amount"
        case campaignPointAmount = "campaign_point_amount"
        case account = "account"
        case description = "description"
        case doneAt = "done_at"
        case type = "type"
        case isModified = "is_modified"
        case transfers = "transfers"
    }
}
