// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct UserTransactionWithCustomerBalance: Codable {
    public let id: String;
    public let user: User;
    public let balance: Int;
    public let customerBalance: Int;
    public let amount: Int;
    public let moneyAmount: Int;
    public let pointAmount: Int;
    public let account: Account;
    public let description: String;
    public let doneAt: String;
    public let type: String;
    public let isModified: Bool;

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case user = "user"
        case balance = "balance"
        case customerBalance = "customer_balance"
        case amount = "amount"
        case moneyAmount = "money_amount"
        case pointAmount = "point_amount"
        case account = "account"
        case description = "description"
        case doneAt = "done_at"
        case type = "type"
        case isModified = "is_modified"
    }
}
