// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct UserTagInformation: Codable {
    public let groupName: String
    public let itemNames: [String]

    private enum CodingKeys: String, CodingKey {
        case groupName = "group_name"
        case itemNames = "item_names"
    }
}
