// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct UserTransferWithoutAccount: Codable {
    public let id: String;
    public let amount: Int;
    public let moneyAmount: Int;
    public let pointAmount: Int;
    public let description: String;
    public let doneAt: String;
    public let type: String;

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case amount = "amount"
        case moneyAmount = "money_amount"
        case pointAmount = "point_amount"
        case description = "description"
        case doneAt = "done_at"
        case type = "type"
    }
}
