// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct UserWithDetails: Codable {
    public let id: String;
    public let name: String;
    public let isMerchant: Bool;
    public let tel: String;
    public let email: String;

    private enum CodingKeys: String, CodingKeys {
        case id = "id"
        case name = "name"
        case isMerchant = "is_merchant"
        case tel = "tel"
        case email = "email"
    }
}
