// DO NOT EDIT: File is generated by code generator.
import Foundation

public struct VeritransMdkTokenApiKey: Codable {
    public let tokenApiKey: String?

    private enum CodingKeys: String, CodingKey {
        case tokenApiKey = "token_api_key"
    }
}
