// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Shop {
    struct GetDetailedShopInformation: BankRequest {
        public let shopId: String

        public typealias Response = DetailedShopInformation

        public init(shopId: String) {
            self.shopId = shopId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/shops/\(shopId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
