// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Shop {
    struct GetListOfShops: BankRequest {
        public let privateMoneyId: String
        public let userTagGroupItemId: String?
        public let before: String
        public let after: String
        public let perPage: Int?

        public typealias Response = PaginatedShops

        public init(privateMoneyId: String, userTagGroupItemId: String? = nil, before: String, after: String, perPage: Int? = nil) {
            self.privateMoneyId = privateMoneyId
            self.userTagGroupItemId = userTagGroupItemId
            self.before = before
            self.after = after
            self.perPage = perPage
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/shops"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["private_money_id"] = privateMoneyId

            if userTagGroupItemId != nil {
                dict["user_tag_group_item_id"] = userTagGroupItemId
            }

            dict["before"] = before

            dict["after"] = after

            if perPage != nil {
                dict["per_page"] = perPage
            }

            return dict
        }
    }
}
