// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Account {
    struct CreateAccount: BankRequest {
        public let name: String?
        public let privateMoneyId: String
        public let externalId: String?

        public typealias Response = AccountDetail

        public init(name: String? = nil, privateMoneyId: String, externalId: String? = nil) {
            self.name = name
            self.privateMoneyId = privateMoneyId
            self.externalId = externalId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/accounts"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if name != nil {
                dict["name"] = name
            }

            dict["private_money_id"] = privateMoneyId

            if externalId != nil {
                dict["external_id"] = externalId
            }

            return dict
        }
    }
}
