// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Account {
    struct CreateAccountCpmToken: BankRequest {
        public let scopes: [String]?
        public let expiresIn: Int?
        public let metadata: String?
        public let keepAlive: Bool?
        public let isShortToken: Bool?
        public let accountId: Uuid

        public typealias Response = CpmToken

        public init(scopes: [String]? = nil, expiresIn: Int? = nil, metadata: String? = nil, keepAlive: Bool? = nil, isShortToken: Bool? = nil, accountId: Uuid) {
            self.scopes = scopes
            self.expiresIn = expiresIn
            self.metadata = metadata
            self.keepAlive = keepAlive
            self.isShortToken = isShortToken
            self.accountId = accountId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/accounts/\(accountId)/cpm"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if scopes != nil {
                dict["scopes"] = scopes
            }

            if expiresIn != nil {
                dict["expires_in"] = expiresIn
            }

            if metadata != nil {
                dict["metadata"] = metadata
            }

            if keepAlive != nil {
                dict["keep_alive"] = keepAlive
            }

            if isShortToken != nil {
                dict["is_short_token"] = isShortToken
            }

            return dict
        }
    }
}
