// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Account {
    struct GetAccountBalances: BankRequest {
        public let accountId: String
        public let before: String?
        public let after: String?
        public let perPage: Int?
        public let expired: BooleanString

        public typealias Response = PaginatedAccountBalances

        public init(accountId: String, before: String? = nil, after: String? = nil, perPage: Int? = nil, expired: BooleanString) {
            self.accountId = accountId
            self.before = before
            self.after = after
            self.perPage = perPage
            self.expired = expired
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/accounts/\(accountId)/balances"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if before != nil {
                dict["before"] = before
            }

            if after != nil {
                dict["after"] = after
            }

            if perPage != nil {
                dict["per_page"] = perPage
            }

            dict["expired"] = expired

            return dict
        }
    }
}
