// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Account {
    struct GetAccountTopupQuotas: BankRequest {
        public let accountId: String
        public let status: String?
        public let showExpiredForFixedPeriod: Bool?
        public let showStartedQuotas: Bool?
        public let isWithinApplicablePeriod: Bool?
        public let isUsableAmountLeft: Bool?

        public typealias Response = NIL

        public init(accountId: String, status: String? = nil, showExpiredForFixedPeriod: Bool? = nil, showStartedQuotas: Bool? = nil, isWithinApplicablePeriod: Bool? = nil, isUsableAmountLeft: Bool? = nil) {
            self.accountId = accountId
            self.status = status
            self.showExpiredForFixedPeriod = showExpiredForFixedPeriod
            self.showStartedQuotas = showStartedQuotas
            self.isWithinApplicablePeriod = isWithinApplicablePeriod
            self.isUsableAmountLeft = isUsableAmountLeft
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/accounts/\(accountId)/topup-quotas"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if status != nil {
                dict["status"] = status
            }

            if showExpiredForFixedPeriod != nil {
                dict["show_expired_for_fixed_period"] = showExpiredForFixedPeriod
            }

            if showStartedQuotas != nil {
                dict["show_started_quotas"] = showStartedQuotas
            }

            if isWithinApplicablePeriod != nil {
                dict["is_within_applicable_period"] = isWithinApplicablePeriod
            }

            if isUsableAmountLeft != nil {
                dict["is_usable_amount_left"] = isUsableAmountLeft
            }

            return dict
        }
    }
}
