// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Account {
    struct GetAccount: BankRequest {
        public let accountId: Uuid

        public typealias Response = AccountDetail

        public init(accountId: Uuid) {
            self.accountId = accountId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/accounts/\(accountId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
