// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Account {
    struct GetAccountTransactions: BankRequest {
        public let accountId: Uuid
        public let before: String?
        public let after: String?
        public let perPage: Int?

        public typealias Response = PaginatedAccountTransactions

        public init(accountId: Uuid, before: String? = nil, after: String? = nil, perPage: Int? = nil) {
            self.accountId = accountId
            self.before = before
            self.after = after
            self.perPage = perPage
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/accounts/\(accountId)/transactions"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if before != nil {
                dict["before"] = before
            }

            if after != nil {
                dict["after"] = after
            }

            if perPage != nil {
                dict["per_page"] = perPage
            }

            return dict
        }
    }
}
