// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Account {
    struct PatchAccountCouponDetail: BankRequest {
        public let isReceived: Bool?
        public let code: String?
        public let accountId: String
        public let couponId: String

        public typealias Response = CouponDetail

        public init(isReceived: Bool? = nil, code: String? = nil, accountId: String, couponId: String) {
            self.isReceived = isReceived
            self.code = code
            self.accountId = accountId
            self.couponId = couponId
        }

        public var method: HTTPMethod {
            return .patch
        }

        public var path: String {
            return "/accounts/\(accountId)/coupons/\(couponId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if isReceived != nil {
                dict["is_received"] = isReceived
            }

            if code != nil {
                dict["code"] = code
            }

            return dict
        }
    }
}
