// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Account {
    struct UpdateAccount: BankRequest {
        public let name: String?
        public let accountId: Uuid

        public typealias Response = AccountDetail

        public init(name: String? = nil, accountId: Uuid) {
            self.name = name
            self.accountId = accountId
        }

        public var method: HTTPMethod {
            return .patch
        }

        public var path: String {
            return "/accounts/\(accountId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if name != nil {
                dict["name"] = name
            }

            return dict
        }
    }
}
