// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Transaction {
    struct CreateTransactionWithCheck: BankRequest {
        public let requestId: String?
        public let checkId: String
        public let accountId: String?
        public let topupQuotaId: Int?

        public typealias Response = Autogen.Responses.UserTransactionWithFallback

        public init(requestId: String? = nil, checkId: String, accountId: String? = nil, topupQuotaId: Int? = nil) {
            self.requestId = requestId
            self.checkId = checkId
            self.accountId = accountId
            self.topupQuotaId = topupQuotaId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/transactions/check"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if requestId != nil {
                dict["request_id"] = requestId
            }

            dict["check_id"] = checkId

            if accountId != nil {
                dict["account_id"] = accountId
            }

            if topupQuotaId != nil {
                dict["topup_quota_id"] = topupQuotaId
            }

            return dict
        }
    }
}
