// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Transaction {
    struct CreateTransactionWithCashtray: BankRequest {
        public let requestId: String
        public let cashtrayId: String
        public let accountId: String?
        public let couponId: String?
        public let strategy: String?
        public let topupQuotaId: Int?

        public typealias Response = Autogen.Responses.UserTransactionWithFallback

        public init(requestId: String, cashtrayId: String, accountId: String? = nil, couponId: String? = nil, strategy: String? = nil, topupQuotaId: Int? = nil) {
            self.requestId = requestId
            self.cashtrayId = cashtrayId
            self.accountId = accountId
            self.couponId = couponId
            self.strategy = strategy
            self.topupQuotaId = topupQuotaId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/transactions/cashtray"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["request_id"] = requestId

            dict["cashtray_id"] = cashtrayId

            if accountId != nil {
                dict["account_id"] = accountId
            }

            if couponId != nil {
                dict["coupon_id"] = couponId
            }

            if strategy != nil {
                dict["strategy"] = strategy
            }

            if topupQuotaId != nil {
                dict["topup_quota_id"] = topupQuotaId
            }

            return dict
        }
    }
}
