// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.User {
    struct GetUserSettingUrl: BankRequest {

        public typealias Response = OauthFullAccessUrl

        public init() {
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/oauth/full-access"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
