// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.User {
    struct GetUserAccounts: BankRequest {
        public let userId: String
        public let before: String?
        public let after: String?
        public let perPage: Int?

        public typealias Response = PaginatedUserAccounts

        public init(userId: String, before: String? = nil, after: String? = nil, perPage: Int? = nil) {
            self.userId = userId
            self.before = before
            self.after = after
            self.perPage = perPage
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/users/\(userId)/accounts"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if before != nil {
                dict["before"] = before
            }

            if after != nil {
                dict["after"] = after
            }

            if perPage != nil {
                dict["per_page"] = perPage
            }

            return dict
        }
    }
}
