// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.User {
    struct GetUser: BankRequest {
        public let userId: String

        public typealias Response = UserWithDetails

        public init(userId: String) {
            self.userId = userId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/users/\(userId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
