// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.User {
    struct UpdateUser: BankRequest {
        public let name: String?
        public let userId: String

        public typealias Response = UserWithDetails

        public init(name: String? = nil, userId: String) {
            self.name = name
            self.userId = userId
        }

        public var method: HTTPMethod {
            return .patch
        }

        public var path: String {
            return "/users/\(userId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if name != nil {
                dict["name"] = name
            }

            return dict
        }
    }
}
