// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.UserTag {
    struct GetUserTagGroupItems: BankRequest {
        public let organizationCode: String
        public let tagGroupId: String
        public let subgroupId: String?
        public let before: String?
        public let after: String?
        public let perPage: Int?

        public typealias Response = Autogen.Responses.PaginatedUserTagGroupItems

        public init(organizationCode: String, tagGroupId: String, subgroupId: String? = nil, before: String? = nil, after: String? = nil, perPage: Int? = nil) {
            self.organizationCode = organizationCode
            self.tagGroupId = tagGroupId
            self.subgroupId = subgroupId
            self.before = before
            self.after = after
            self.perPage = perPage
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/user-tag-groups/\(organizationCode)/items"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["tag_group_id"] = tagGroupId

            if subgroupId != nil {
                dict["subgroup_id"] = subgroupId
            }

            if before != nil {
                dict["before"] = before
            }

            if after != nil {
                dict["after"] = after
            }

            if perPage != nil {
                dict["per_page"] = perPage
            }

            return dict
        }
    }
}
