// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Cashtray {
    struct GetCashtrayAttempts: BankRequest {
        public let cashtrayId: String

        public typealias Response = Autogen.Responses.CashtrayAttempts

        public init(cashtrayId: String) {
            self.cashtrayId = cashtrayId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/cashtrays/\(cashtrayId)/attempts"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
