// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Cashtray {
    struct CreateCashtray: BankRequest {
        public let amount: Double
        public let description: String?
        public let expiresIn: Int?
        public let products: [Product]?
        public let metadata: String?

        public typealias Response = Autogen.Responses.Cashtray

        public init(amount: Double, description: String? = nil, expiresIn: Int? = nil, products: [Product]? = nil, metadata: String? = nil) {
            self.amount = amount
            self.description = description
            self.expiresIn = expiresIn
            self.products = products
            self.metadata = metadata
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/cashtrays"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["amount"] = amount

            if description != nil {
                dict["description"] = description
            }

            if expiresIn != nil {
                dict["expires_in"] = expiresIn
            }

            if products != nil {
                dict["products"] = products
            }

            if metadata != nil {
                dict["metadata"] = metadata
            }

            return dict
        }
    }
}
