// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.PrivateMoney {
    struct GetPrivateMoneyPaymentAct: BankRequest {
        public let privateMoneyId: Uuid

        public typealias Response = NIL

        public init(privateMoneyId: Uuid) {
            self.privateMoneyId = privateMoneyId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/private-moneys/\(privateMoneyId)/payment-act"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
