// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.PrivateMoney {
    struct GetPrivateMoneyCommercialAct: BankRequest {
        public let privateMoneyId: String

        public typealias Response = PrivateMoneyLegalText

        public init(privateMoneyId: String) {
            self.privateMoneyId = privateMoneyId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/private-moneys/\(privateMoneyId)/commercial-act"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
