// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.PrivateMoney {
    struct ListPrivateMoneys: BankRequest {
        public let name: String?
        public let includeExclusive: Bool?
        public let before: Uuid
        public let after: Uuid
        public let perPage: Int?

        public typealias Response = PaginatedPrivateMoneys

        public init(name: String? = nil, includeExclusive: Bool? = nil, before: Uuid, after: Uuid, perPage: Int? = nil) {
            self.name = name
            self.includeExclusive = includeExclusive
            self.before = before
            self.after = after
            self.perPage = perPage
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/private-moneys"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if name != nil {
                dict["name"] = name
            }

            if includeExclusive != nil {
                dict["include_exclusive"] = includeExclusive
            }

            dict["before"] = before

            dict["after"] = after

            if perPage != nil {
                dict["per_page"] = perPage
            }

            return dict
        }
    }
}
