// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Bill {
    struct CreateBill: BankRequest {
        public let amount: Int?
        public let accountId: String?
        public let additionalAccountIds: [String]?
        public let description: String?
        public let isOnetime: Bool?
        public let minAmount: Int?
        public let maxAmount: Int?
        public let products: [Product]?
        public let metadata: String?

        public typealias Response = Bill

        public init(amount: Int? = nil, accountId: String? = nil, additionalAccountIds: [String]? = nil, description: String? = nil, isOnetime: Bool? = nil, minAmount: Int? = nil, maxAmount: Int? = nil, products: [Product]? = nil, metadata: String? = nil) {
            self.amount = amount
            self.accountId = accountId
            self.additionalAccountIds = additionalAccountIds
            self.description = description
            self.isOnetime = isOnetime
            self.minAmount = minAmount
            self.maxAmount = maxAmount
            self.products = products
            self.metadata = metadata
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/bills"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if amount != nil {
                dict["amount"] = amount
            }

            if accountId != nil {
                dict["account_id"] = accountId
            }

            if additionalAccountIds != nil {
                dict["additional_account_ids"] = additionalAccountIds
            }

            if description != nil {
                dict["description"] = description
            }

            if isOnetime != nil {
                dict["is_onetime"] = isOnetime
            }

            if minAmount != nil {
                dict["min_amount"] = minAmount
            }

            if maxAmount != nil {
                dict["max_amount"] = maxAmount
            }

            if products != nil {
                dict["products"] = products
            }

            if metadata != nil {
                dict["metadata"] = metadata
            }

            return dict
        }
    }
}
