// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Bill {
    struct DeleteBill: BankRequest {
        public let billId: String

        public typealias Response = NoContent

        public init(billId: String) {
            self.billId = billId
        }

        public var method: HTTPMethod {
            return .delete
        }

        public var path: String {
            return "/bills/\(billId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
