// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Bill {
    struct GetBill: BankRequest {
        public let billId: String
        public let privateMoneyId: String?

        public typealias Response = BillWithAdditionalPrivateMoneys

        public init(billId: String, privateMoneyId: String? = nil) {
            self.billId = billId
            self.privateMoneyId = privateMoneyId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/bills/\(billId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if privateMoneyId != nil {
                dict["private_money_id"] = privateMoneyId
            }

            return dict
        }
    }
}
