// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Bill {
    struct UpdateBill: BankRequest {
        public let amount: Int?
        public let description: String?
        public let products: [Product]?
        public let billId: String

        public typealias Response = Bill

        public init(amount: Int? = nil, description: String? = nil, products: [Product]? = nil, billId: String) {
            self.amount = amount
            self.description = description
            self.products = products
            self.billId = billId
        }

        public var method: HTTPMethod {
            return .patch
        }

        public var path: String {
            return "/bills/\(billId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if amount != nil {
                dict["amount"] = amount
            }

            if description != nil {
                dict["description"] = description
            }

            if products != nil {
                dict["products"] = products
            }

            return dict
        }
    }
}
