// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct BankPaySession: Codable {
        public let redirectUrl: String
        public let paytreeCustomerNumber: String

        private enum CodingKeys: String, CodingKey {
            case redirectUrl = "redirect_url"
            case paytreeCustomerNumber = "paytree_customer_number"
        }
    }
}
