// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct PrivateMoneyDetail: Codable {
        public let id: String
        public let name: String
        public let type: String
        public let unit: String
        public let description: String
        public let onelineMessage: String
        public let displayMoneyAndPoint: String
        public let customDomainName: String?
        public let canUseC2cTransfer: Bool
        public let accountImage: String?
        public let images: PrivateMoneyImages
        public let sounds: PrivateMoneySounds
        public let organization: Organization
        public let maxBalance: Double
        public let transferLimit: Double
        public let moneyTopupTransferLimit: Double
        public let expirationType: String
        public let isExclusive: Bool
        public let termsUrl: String?
        public let privacyPolicyUrl: String?
        public let paymentActUrl: String?
        public let commercialActUrl: String?
        public let isTopupQuotaAvailable: Bool
        public let isItrustAuthenticationEnabled: Bool
        public let canUseCreditCard: Bool
        public let topupMethods: [PrivateMoneyTopupMethod]
        public let fallbackMoneys: [FallbackPrivateMoney]

        private enum CodingKeys: String, CodingKey {
            case id = "id"
            case name = "name"
            case type = "type"
            case unit = "unit"
            case description = "description"
            case onelineMessage = "oneline_message"
            case displayMoneyAndPoint = "display_money_and_point"
            case customDomainName = "custom_domain_name"
            case canUseC2cTransfer = "can_use_c2c_transfer"
            case accountImage = "account_image"
            case images = "images"
            case sounds = "sounds"
            case organization = "organization"
            case maxBalance = "max_balance"
            case transferLimit = "transfer_limit"
            case moneyTopupTransferLimit = "money_topup_transfer_limit"
            case expirationType = "expiration_type"
            case isExclusive = "is_exclusive"
            case termsUrl = "terms_url"
            case privacyPolicyUrl = "privacy_policy_url"
            case paymentActUrl = "payment_act_url"
            case commercialActUrl = "commercial_act_url"
            case isTopupQuotaAvailable = "is_topup_quota_available"
            case isItrustAuthenticationEnabled = "is_itrust_authentication_enabled"
            case canUseCreditCard = "can_use_credit_card"
            case topupMethods = "topup_methods"
            case fallbackMoneys = "fallback_moneys"
        }
    }
}
