// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct UserWithAuthFactors: Codable {
        public let id: String
        public let name: String
        public let isMerchant: Bool
        public let tel: String?
        public let countryCode: String?
        public let email: String?
        public let isPasswordRegistered: Bool

        private enum CodingKeys: String, CodingKey {
            case id = "id"
            case name = "name"
            case isMerchant = "is_merchant"
            case tel = "tel"
            case countryCode = "country_code"
            case email = "email"
            case isPasswordRegistered = "is_password_registered"
        }
    }
}
