// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct UserTransfer: Codable {
        public let id: String
        public let transactionId: String
        public let user: User
        public let balance: Double
        public let amount: Double
        public let moneyAmount: Double
        public let pointAmount: Double
        public let account: Account
        public let description: String
        public let doneAt: String
        public let type: String

        private enum CodingKeys: String, CodingKey {
            case id = "id"
            case transactionId = "transaction_id"
            case user = "user"
            case balance = "balance"
            case amount = "amount"
            case moneyAmount = "money_amount"
            case pointAmount = "point_amount"
            case account = "account"
            case description = "description"
            case doneAt = "done_at"
            case type = "type"
        }
    }
}
