// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct UserTagInformation: Codable {
        public let groupName: String
        public let itemNames: [String]

        private enum CodingKeys: String, CodingKey {
            case groupName = "group_name"
            case itemNames = "item_names"
        }
    }
}
