// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct UserTagSubgroup: Codable {
        public let subgroupName: String
        public let id: String

        private enum CodingKeys: String, CodingKey {
            case subgroupName = "subgroup_name"
            case id = "id"
        }
    }
}
