// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct CouponInfo: Codable {
        public let id: String
        public let name: String
        public let description: String
        public let discountAmount: Double?
        public let discountPercentage: Double?
        public let startsAt: String
        public let endsAt: String
        public let displayStartsAt: String
        public let displayEndsAt: String
        public let usageLimit: Double?
        public let minAmount: Double?
        public let isShopSpecified: Bool
        public let isPublic: Bool
        public let isDisabled: Bool
        public let isHidden: Bool
        public let couponImage: String?
        public let privateMoneyId: String
        public let availableShops: [User]

        private enum CodingKeys: String, CodingKey {
            case id = "id"
            case name = "name"
            case description = "description"
            case discountAmount = "discount_amount"
            case discountPercentage = "discount_percentage"
            case startsAt = "starts_at"
            case endsAt = "ends_at"
            case displayStartsAt = "display_starts_at"
            case displayEndsAt = "display_ends_at"
            case usageLimit = "usage_limit"
            case minAmount = "min_amount"
            case isShopSpecified = "is_shop_specified"
            case isPublic = "is_public"
            case isDisabled = "is_disabled"
            case isHidden = "is_hidden"
            case couponImage = "coupon_image"
            case privateMoneyId = "private_money_id"
            case availableShops = "available_shops"
        }
    }
}
