// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct IdentificationMatch: Codable {
        public let name: Bool
        public let gender: Bool
        public let address: Bool
        public let dateOfBirth: Bool

        private enum CodingKeys: String, CodingKey {
            case name = "name"
            case gender = "gender"
            case address = "address"
            case dateOfBirth = "date_of_birth"
        }
    }
}
