// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct VeritransMdkTokenApiKey: Codable {
        public let tokenApiKey: String?

        private enum CodingKeys: String, CodingKey {
            case tokenApiKey = "token_api_key"
        }
    }
}
