// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct PrivateMoneySounds: Codable {
        public let payment: String?

        private enum CodingKeys: String, CodingKey {
            case payment = "payment"
        }
    }
}
