// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct UserTransferWithoutAccount: Codable {
        public let id: String
        public let amount: Double
        public let moneyAmount: Double
        public let pointAmount: Double
        public let description: String
        public let doneAt: String
        public let type: String

        private enum CodingKeys: String, CodingKey {
            case id = "id"
            case amount = "amount"
            case moneyAmount = "money_amount"
            case pointAmount = "point_amount"
            case description = "description"
            case doneAt = "done_at"
            case type = "type"
        }
    }
}
