// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct CashtrayAttempts: Codable {
        public let rows: [CashtrayAttempt]

        private enum CodingKeys: String, CodingKey {
            case rows = "rows"
        }
    }
}
