// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct IndividualNumberIdentificationError: Codable {
        public let type: String
        public let message: String
        public let errorCode: Int
        public let errorMessage: String

        private enum CodingKeys: String, CodingKey {
            case type = "type"
            case message = "message"
            case errorCode = "error_code"
            case errorMessage = "error_message"
        }
    }
}
