// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct UserTagGroup: Codable {
        public let groupName: String
        public let id: String
        public let hasSubgroups: Bool

        private enum CodingKeys: String, CodingKey {
            case groupName = "group_name"
            case id = "id"
            case hasSubgroups = "has_subgroups"
        }
    }
}
