// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct IdentificationResult: Codable {
        public let isValid: Bool
        public let identifiedAt: String?
        public let match: IdentificationMatch
        public let isResident: Bool

        private enum CodingKeys: String, CodingKey {
            case isValid = "is_valid"
            case identifiedAt = "identified_at"
            case match = "match"
            case isResident = "is_resident"
        }
    }
}
