// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct Organization: Codable {
        public let code: String
        public let name: String

        private enum CodingKeys: String, CodingKey {
            case code = "code"
            case name = "name"
        }
    }
}
