// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct PrivateMoneyLegalText: Codable {
        public let text: String

        private enum CodingKeys: String, CodingKey {
            case text = "text"
        }
    }
}
