// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct PrivateMoneyImages: Codable {
        public let card: String?
        public let n300x300: String?
        public let n600x600: String?

        private enum CodingKeys: String, CodingKey {
            case card = "card"
            case n300x300 = "300x300"
            case n600x600 = "600x600"
        }
    }
}
