// DO NOT EDIT: File is generated by code generator.
import Foundation

public extension Autogen.Responses {
    struct FallbackPrivateMoney: Codable {
        public let name: String
        public let id: String

        private enum CodingKeys: String, CodingKey {
            case name = "name"
            case id = "id"
        }
    }
}
