// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Terminal {
    struct GetTerminalById: BankRequest {
        public let terminalId: String

        public typealias Response = Autogen.Responses.Terminal

        public init(terminalId: String) {
            self.terminalId = terminalId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/terminals/\(terminalId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
