// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Terminal {
    struct GetTerminal: BankRequest {

        public typealias Response = Autogen.Responses.Terminal

        public init() {
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/terminal"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
