// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Cvs {
    struct CVSAuthorizeRequest: BankRequest {
        public let serviceOptionType: String
        public let amount: Int
        public let name1: String
        public let name2: String
        public let tel: String
        public let topupQuotaId: Int?
        public let accountId: String

        public typealias Response = CvsAuthorization

        public init(serviceOptionType: String, amount: Int, name1: String, name2: String, tel: String, topupQuotaId: Int? = nil, accountId: String) {
            self.serviceOptionType = serviceOptionType
            self.amount = amount
            self.name1 = name1
            self.name2 = name2
            self.tel = tel
            self.topupQuotaId = topupQuotaId
            self.accountId = accountId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/accounts/\(accountId)/cvs"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["service_option_type"] = serviceOptionType

            dict["amount"] = amount

            dict["name1"] = name1

            dict["name2"] = name2

            dict["tel"] = tel

            if topupQuotaId != nil {
                dict["topup_quota_id"] = topupQuotaId
            }

            return dict
        }
    }
}
