// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Check {
    struct CreateCheck: BankRequest {
        public let amount: Int?
        public let moneyAmount: Int?
        public let pointAmount: Int?
        public let accountId: String?
        public let description: String?
        public let isOnetime: Bool?
        public let usageLimit: Int?
        public let expiresAt: String?
        public let pointExpiresAt: String?
        public let pointExpiresInDays: Int?
        public let metadata: String?

        public typealias Response = Check

        public init(amount: Int? = nil, moneyAmount: Int? = nil, pointAmount: Int? = nil, accountId: String? = nil, description: String? = nil, isOnetime: Bool? = nil, usageLimit: Int? = nil, expiresAt: String? = nil, pointExpiresAt: String? = nil, pointExpiresInDays: Int? = nil, metadata: String? = nil) {
            self.amount = amount
            self.moneyAmount = moneyAmount
            self.pointAmount = pointAmount
            self.accountId = accountId
            self.description = description
            self.isOnetime = isOnetime
            self.usageLimit = usageLimit
            self.expiresAt = expiresAt
            self.pointExpiresAt = pointExpiresAt
            self.pointExpiresInDays = pointExpiresInDays
            self.metadata = metadata
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/checks"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if amount != nil {
                dict["amount"] = amount
            }

            if moneyAmount != nil {
                dict["money_amount"] = moneyAmount
            }

            if pointAmount != nil {
                dict["point_amount"] = pointAmount
            }

            if accountId != nil {
                dict["account_id"] = accountId
            }

            if description != nil {
                dict["description"] = description
            }

            if isOnetime != nil {
                dict["is_onetime"] = isOnetime
            }

            if usageLimit != nil {
                dict["usage_limit"] = usageLimit
            }

            if expiresAt != nil {
                dict["expires_at"] = expiresAt
            }

            if pointExpiresAt != nil {
                dict["point_expires_at"] = pointExpiresAt
            }

            if pointExpiresInDays != nil {
                dict["point_expires_in_days"] = pointExpiresInDays
            }

            if metadata != nil {
                dict["metadata"] = metadata
            }

            return dict
        }
    }
}
