// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Check {
    struct DeleteCheck: BankRequest {
        public let checkId: String

        public typealias Response = NoContent

        public init(checkId: String) {
            self.checkId = checkId
        }

        public var method: HTTPMethod {
            return .delete
        }

        public var path: String {
            return "/checks/\(checkId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
