// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Check {
    struct UpdateCheck: BankRequest {
        public let amount: Int?
        public let description: String?
        public let expiresAt: String?
        public let pointExpiresAt: String?
        public let pointExpiresInDays: Int?
        public let checkId: String

        public typealias Response = Check

        public init(amount: Int? = nil, description: String? = nil, expiresAt: String? = nil, pointExpiresAt: String? = nil, pointExpiresInDays: Int? = nil, checkId: String) {
            self.amount = amount
            self.description = description
            self.expiresAt = expiresAt
            self.pointExpiresAt = pointExpiresAt
            self.pointExpiresInDays = pointExpiresInDays
            self.checkId = checkId
        }

        public var method: HTTPMethod {
            return .patch
        }

        public var path: String {
            return "/checks/\(checkId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if amount != nil {
                dict["amount"] = amount
            }

            if description != nil {
                dict["description"] = description
            }

            if expiresAt != nil {
                dict["expires_at"] = expiresAt
            }

            if pointExpiresAt != nil {
                dict["point_expires_at"] = pointExpiresAt
            }

            if pointExpiresInDays != nil {
                dict["point_expires_in_days"] = pointExpiresInDays
            }

            return dict
        }
    }
}
