// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Bank {
    struct BankTopUp: BankRequest {
        public let accountId: String
        public let bankId: String
        public let amount: Int
        public let requestId: String?
        public let userId: String

        public typealias Response = UserTransaction

        public init(accountId: String, bankId: String, amount: Int, requestId: String? = nil, userId: String) {
            self.accountId = accountId
            self.bankId = bankId
            self.amount = amount
            self.requestId = requestId
            self.userId = userId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/users/\(userId)/banks/topup"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["account_id"] = accountId

            dict["bank_id"] = bankId

            dict["amount"] = amount

            if requestId != nil {
                dict["request_id"] = requestId
            }

            return dict
        }
    }
}
