// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Bank {
    struct DeleteBank: BankRequest {
        public let bankId: String
        public let userId: String

        public typealias Response = NoContent

        public init(bankId: String, userId: String) {
            self.bankId = bankId
            self.userId = userId
        }

        public var method: HTTPMethod {
            return .delete
        }

        public var path: String {
            return "/users/\(userId)/banks"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["bank_id"] = bankId

            return dict
        }
    }
}
