// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Bank {
    struct ListBanks: BankRequest {
        public let userId: String
        public let privateMoneyId: String?

        public typealias Response = UserBanks

        public init(userId: String, privateMoneyId: String? = nil) {
            self.userId = userId
            self.privateMoneyId = privateMoneyId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/users/\(userId)/banks"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if privateMoneyId != nil {
                dict["private_money_id"] = privateMoneyId
            }

            return dict
        }
    }
}
