// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.CreditCard {
    struct CreditWithCreditCardMembership: BankRequest {
        public let userId: String
        public let cardRegisteredAt: String?
        public let cardUuid: String?
        public let organizationCode: String?

        public typealias Response = String

        public init(userId: String, cardRegisteredAt: String? = nil, cardUuid: String? = nil, organizationCode: String? = nil) {
            self.userId = userId
            self.cardRegisteredAt = cardRegisteredAt
            self.cardUuid = cardUuid
            self.organizationCode = organizationCode
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/veritrans/card-authorize/credit-with-membership"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["user_id"] = userId

            if cardRegisteredAt != nil {
                dict["card_registered_at"] = cardRegisteredAt
            }

            if cardUuid != nil {
                dict["card_uuid"] = cardUuid
            }

            if organizationCode != nil {
                dict["organization_code"] = organizationCode
            }

            return dict
        }

        public var responseContentType: String {
            return "text/html"
        }
    }
}
