// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.CreditCard {
    struct TopupWithCreditCard: BankRequest {
        public let accountId: String
        public let amount: Int
        public let cardRegisteredAt: String?
        public let cardUuid: String?
        public let organizationCode: String?
        public let userId: String

        public typealias Response = Autogen.Responses.UserTransaction

        public init(accountId: String, amount: Int, cardRegisteredAt: String? = nil, cardUuid: String? = nil, organizationCode: String? = nil, userId: String) {
            self.accountId = accountId
            self.amount = amount
            self.cardRegisteredAt = cardRegisteredAt
            self.cardUuid = cardUuid
            self.organizationCode = organizationCode
            self.userId = userId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/users/\(userId)/cards/topup"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["account_id"] = accountId

            dict["amount"] = amount

            if cardRegisteredAt != nil {
                dict["card_registered_at"] = cardRegisteredAt
            }

            if cardUuid != nil {
                dict["card_uuid"] = cardUuid
            }

            if organizationCode != nil {
                dict["organization_code"] = organizationCode
            }

            return dict
        }
    }
}
