// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.CreditCard {
    struct GetVeritransMdkTokenApiKey: BankRequest {
        public let organizationCode: String?

        public typealias Response = Autogen.Responses.VeritransMdkTokenApiKey

        public init(organizationCode: String? = nil) {
            self.organizationCode = organizationCode
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/veritrans/mdk-token-api-key"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if organizationCode != nil {
                dict["organization_code"] = organizationCode
            }

            return dict
        }
    }
}
