// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Cvs {
    struct GetCvsAuthorization: BankRequest {
        public let accountId: String
        public let orderId: String

        public typealias Response = Autogen.Responses.CvsAuthorization

        public init(accountId: String, orderId: String) {
            self.accountId = accountId
            self.orderId = orderId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/accounts/\(accountId)/cvs/\(orderId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
