// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Cpm {
    struct GetCpmToken: BankRequest {
        public let cpmToken: String

        public typealias Response = CpmToken

        public init(cpmToken: String) {
            self.cpmToken = cpmToken
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/cpm/\(cpmToken)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
