// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Jihanpi {
    struct GetJihanpiTransactionByOrderId: BankRequest {
        public let orderId: String

        public typealias Response = Autogen.Responses.JihanpiTransaction

        public init(orderId: String) {
            self.orderId = orderId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/jihanpi-transactions/\(orderId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
