// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.User {
    struct DeleteUser: BankRequest {
        public let userId: String

        public typealias Response = NoContent

        public init(userId: String) {
            self.userId = userId
        }

        public var method: HTTPMethod {
            return .delete
        }

        public var path: String {
            return "/users/\(userId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
