// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Campaign {
    struct GetAccountCampaignPointAmounts: BankRequest {
        public let accountId: String
        public let campaignId: String

        public typealias Response = Autogen.Responses.AccountCampaignPointAmounts

        public init(accountId: String, campaignId: String) {
            self.accountId = accountId
            self.campaignId = campaignId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/accounts/\(accountId)/campaigns/\(campaignId)/point-amounts"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
