// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Terminal {
    struct AddTerminalPublicKey: BankRequest {
        public let key: String

        public typealias Response = TerminalServerKey

        public init(key: String) {
            self.key = key
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/terminal/keys"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["key"] = key

            return dict
        }
    }
}
