// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Terminal {
    struct UpdateTerminal: BankRequest {
        public let name: String?
        public let accountId: String?
        public let pushService: String?
        public let pushToken: String?

        public typealias Response = Terminal

        public init(name: String? = nil, accountId: String? = nil, pushService: String? = nil, pushToken: String? = nil) {
            self.name = name
            self.accountId = accountId
            self.pushService = pushService
            self.pushToken = pushToken
        }

        public var method: HTTPMethod {
            return .patch
        }

        public var path: String {
            return "/terminal"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if name != nil {
                dict["name"] = name
            }

            if accountId != nil {
                dict["account_id"] = accountId
            }

            if pushService != nil {
                dict["push_service"] = pushService
            }

            if pushToken != nil {
                dict["push_token"] = pushToken
            }

            return dict
        }
    }
}
