// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Cashtray {
    struct CreateCashtray: BankRequest {
        public let amount: Int
        public let description: String?
        public let expiresIn: Int?

        public typealias Response = Cashtray

        public init(amount: Int, description: String? = nil, expiresIn: Int? = nil) {
            self.amount = amount
            self.description = description
            self.expiresIn = expiresIn
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/cashtrays"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["amount"] = amount

            if description != nil {
                dict["description"] = description
            }

            if expiresIn != nil {
                dict["expires_in"] = expiresIn
            }

            return dict
        }
    }
}
