// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Cashtray {
    struct GetCashtray: BankRequest {
        public let cashtrayId: String

        public typealias Response = CashtrayWithAttemptAndTransaction

        public init(cashtrayId: String) {
            self.cashtrayId = cashtrayId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/cashtrays/\(cashtrayId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
