// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Cashtray {
    struct UpdateCashtray: BankRequest {
        public let amount: Int?
        public let description: String?
        public let expiresIn: Int?
        public let products: [Product]?
        public let cashtrayId: String

        public typealias Response = Cashtray

        public init(amount: Int? = nil, description: String? = nil, expiresIn: Int? = nil, products: [Product]? = nil, cashtrayId: String) {
            self.amount = amount
            self.description = description
            self.expiresIn = expiresIn
            self.products = products
            self.cashtrayId = cashtrayId
        }

        public var method: HTTPMethod {
            return .patch
        }

        public var path: String {
            return "/cashtrays/\(cashtrayId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if amount != nil {
                dict["amount"] = amount
            }

            if description != nil {
                dict["description"] = description
            }

            if expiresIn != nil {
                dict["expires_in"] = expiresIn
            }

            if products != nil {
                dict["products"] = products
            }

            return dict
        }
    }
}
