// DO NOT EDIT: File is generated by code generator.

public enum Autogen {
    public enum Responses {}

    public enum BankAPI {
        public enum Account {}
        public enum Bank {}
        public enum Bill {}
        public enum Campaign {}
        public enum Cashtray {}
        public enum Check {}
        public enum Coupon {}
        public enum Cpm {}
        public enum CreditCard {}
        public enum Cvs {}
        public enum Jihanpi {}
        public enum Merchants {}
        public enum PrivateMoney {}
        public enum Shop {}
        public enum Terminal {}
        public enum Transaction {}
        public enum User {}
        public enum UserTag {}
    }
}
