// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.UserTag {
    struct GetUserTagGroupItems: BankRequest {
        public let organizationCode: String
        public let tagGroupId: Uuid
        public let before: Uuid
        public let after: Uuid
        public let perPage: Int?

        public typealias Response = PaginatedUserTagGroupItems

        public init(organizationCode: String, tagGroupId: Uuid, before: Uuid, after: Uuid, perPage: Int? = nil) {
            self.organizationCode = organizationCode
            self.tagGroupId = tagGroupId
            self.before = before
            self.after = after
            self.perPage = perPage
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/user-tag-groups/\(organizationCode)/items"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["tag_group_id"] = tagGroupId

            dict["before"] = before

            dict["after"] = after

            if perPage != nil {
                dict["per_page"] = perPage
            }

            return dict
        }
    }
}
