// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.UserTag {
    struct GetUserTagGroups: BankRequest {
        public let privateMoneyId: String
        public let before: String?
        public let after: String?
        public let perPage: Int?

        public typealias Response = PaginatedUserTagGroups

        public init(privateMoneyId: String, before: String? = nil, after: String? = nil, perPage: Int? = nil) {
            self.privateMoneyId = privateMoneyId
            self.before = before
            self.after = after
            self.perPage = perPage
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/user-tag-groups"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["private_money_id"] = privateMoneyId

            if before != nil {
                dict["before"] = before
            }

            if after != nil {
                dict["after"] = after
            }

            if perPage != nil {
                dict["per_page"] = perPage
            }

            return dict
        }
    }
}
