// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.CreditCard {
    struct CreateCreditCard: BankRequest {
        public let token: String
        public let isCardholderNameSpecified: Bool?
        public let organizationCode: String
        public let userId: String

        public typealias Response = CreditCard

        public init(token: String, isCardholderNameSpecified: Bool? = nil, organizationCode: String, userId: String) {
            self.token = token
            self.isCardholderNameSpecified = isCardholderNameSpecified
            self.organizationCode = organizationCode
            self.userId = userId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/users/\(userId)/cards"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["token"] = token

            if isCardholderNameSpecified != nil {
                dict["is_cardholder_name_specified"] = isCardholderNameSpecified
            }

            dict["organization_code"] = organizationCode

            return dict
        }
    }
}
