// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.CreditCard {
    struct GetCreditCards: BankRequest {
        public let userId: String
        public let before: String?
        public let after: String?
        public let perPage: Int?
        public let organizationCode: String?

        public typealias Response = PaginatedCreditCards

        public init(userId: String, before: String? = nil, after: String? = nil, perPage: Int? = nil, organizationCode: String? = nil) {
            self.userId = userId
            self.before = before
            self.after = after
            self.perPage = perPage
            self.organizationCode = organizationCode
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/users/\(userId)/cards"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if before != nil {
                dict["before"] = before
            }

            if after != nil {
                dict["after"] = after
            }

            if perPage != nil {
                dict["per_page"] = perPage
            }

            if organizationCode != nil {
                dict["organization_code"] = organizationCode
            }

            return dict
        }
    }
}
