// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.CreditCard {
    struct TopupWithCreditCardMdkToken: BankRequest {
        public let userId: String
        public let token: String
        public let accountId: String
        public let amount: Int
        public let organizationCode: String
        public let isCardholderNameSpecified: Bool?
        public let requestId: String?
        public let topupQuotaId: Int?

        public typealias Response = String

        public init(userId: String, token: String, accountId: String, amount: Int, organizationCode: String, isCardholderNameSpecified: Bool? = nil, requestId: String? = nil, topupQuotaId: Int? = nil) {
            self.userId = userId
            self.token = token
            self.accountId = accountId
            self.amount = amount
            self.organizationCode = organizationCode
            self.isCardholderNameSpecified = isCardholderNameSpecified
            self.requestId = requestId
            self.topupQuotaId = topupQuotaId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/veritrans/card-authorize/topup-with-mdk-token"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["user_id"] = userId

            dict["token"] = token

            dict["account_id"] = accountId

            dict["amount"] = amount

            dict["organization_code"] = organizationCode

            if isCardholderNameSpecified != nil {
                dict["is_cardholder_name_specified"] = isCardholderNameSpecified
            }

            if requestId != nil {
                dict["request_id"] = requestId
            }

            if topupQuotaId != nil {
                dict["topup_quota_id"] = topupQuotaId
            }

            return dict
        }

        public var responseContentType: String {
            return "text/html"
        }
    }
}
