// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.CreditCard {
    struct TopupWithCreditCardMdkToken: BankRequest {
        public let userId: String
        public let token: String
        public let accountId: String
        public let amount: Int
        public let requestId: String
        public let organizationCode: String?
        public let isCardholderNameSpecified: Bool?

        public typealias Response = String

        public init(userId: String, token: String, accountId: String, amount: Int, requestId: String, organizationCode: String? = nil, isCardholderNameSpecified: Bool? = nil) {
            self.userId = userId
            self.token = token
            self.accountId = accountId
            self.amount = amount
            self.requestId = requestId
            self.organizationCode = organizationCode
            self.isCardholderNameSpecified = isCardholderNameSpecified
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/veritrans/card-authorize/topup-with-mdk-token"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["user_id"] = userId

            dict["token"] = token

            dict["account_id"] = accountId

            dict["amount"] = amount

            dict["request_id"] = requestId

            if organizationCode != nil {
                dict["organization_code"] = organizationCode
            }

            if isCardholderNameSpecified != nil {
                dict["is_cardholder_name_specified"] = isCardholderNameSpecified
            }

            return dict
        }

        public var responseContentType: String {
            return "text/html"
        }
    }
}
