// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.CreditCard {
    struct TopupWithCreditCardMembership: BankRequest {
        public let userId: String
        public let cardRegisteredAt: String
        public let accountId: String
        public let amount: Int
        public let deleteCardIfAuthFail: Bool?
        public let organizationCode: String
        public let requestId: String?

        public typealias Response = String

        public init(userId: String, cardRegisteredAt: String, accountId: String, amount: Int, deleteCardIfAuthFail: Bool? = nil, organizationCode: String, requestId: String? = nil) {
            self.userId = userId
            self.cardRegisteredAt = cardRegisteredAt
            self.accountId = accountId
            self.amount = amount
            self.deleteCardIfAuthFail = deleteCardIfAuthFail
            self.organizationCode = organizationCode
            self.requestId = requestId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/veritrans/card-authorize/topup-with-membership"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["user_id"] = userId

            dict["card_registered_at"] = cardRegisteredAt

            dict["account_id"] = accountId

            dict["amount"] = amount

            if deleteCardIfAuthFail != nil {
                dict["delete_card_if_auth_fail"] = deleteCardIfAuthFail
            }

            dict["organization_code"] = organizationCode

            if requestId != nil {
                dict["request_id"] = requestId
            }

            return dict
        }

        public var responseContentType: String {
            return "text/html"
        }
    }
}
