// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Coupon {
    struct GetCouponDetail: BankRequest {
        public let couponId: String

        public typealias Response = CouponInfo

        public init(couponId: String) {
            self.couponId = couponId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/coupons/\(couponId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
