// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Transaction {
    struct CreateBillTransaction: BankRequest {
        public let requestId: String
        public let billId: String
        public let accountId: String?
        public let amount: Double?
        public let couponId: String?
        public let strategy: String?

        public typealias Response = UserTransactionWithFallback

        public init(requestId: String, billId: String, accountId: String? = nil, amount: Double? = nil, couponId: String? = nil, strategy: String? = nil) {
            self.requestId = requestId
            self.billId = billId
            self.accountId = accountId
            self.amount = amount
            self.couponId = couponId
            self.strategy = strategy
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/transactions/bill"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["request_id"] = requestId

            dict["bill_id"] = billId

            if accountId != nil {
                dict["account_id"] = accountId
            }

            if amount != nil {
                dict["amount"] = amount
            }

            if couponId != nil {
                dict["coupon_id"] = couponId
            }

            if strategy != nil {
                dict["strategy"] = strategy
            }

            return dict
        }
    }
}
