// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Transaction {
    struct GetTransaction: BankRequest {
        public let transactionId: String

        public typealias Response = UserTransaction

        public init(transactionId: String) {
            self.transactionId = transactionId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/transactions/\(transactionId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
