// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Transaction {
    struct GetTransactionByRequestId: BankRequest {
        public let requestId: String

        public typealias Response = UserTransactionWithTransfers

        public init(requestId: String) {
            self.requestId = requestId
        }

        public var method: HTTPMethod {
            return .get
        }

        public var path: String {
            return "/transactions/requests/\(requestId)"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            return dict
        }
    }
}
