// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension BankAPI.Transaction {
    struct RefundTransaction: BankRequest {
        public let amount: Int?
        public let transactionId: String

        public typealias Response = UserTransaction

        public init(amount: Int? = nil, transactionId: String) {
            self.amount = amount
            self.transactionId = transactionId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/transactions/\(transactionId)/refund"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if amount != nil {
                dict["amount"] = amount
            }

            return dict
        }
    }
}
