// DO NOT EDIT: File is generated by code generator.

public struct BankAPI {
    public struct Account {}
    public struct CreditCard {}
    public struct Cvs {}
    public struct Jihanpi {}
    public struct Shop {}
    public struct Transaction {}
    public struct UserTag {}
}
