// DO NOT EDIT: File is generated by code generator.

public struct BankAPI {
    public struct Account {}
    public struct Bank {}
    public struct Bill {}
    public struct Campaign {}
    public struct Cashtray {}
    public struct Check {}
    public struct Coupon {}
    public struct Cpm {}
    public struct CpmToken {}
    public struct CreditCard {}
    public struct Merchants {}
    public struct PrivateMoney {}
    public struct Terminal {}
    public struct Transaction {}
    public struct User {}
}
