// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Account {
    struct SendToAccount: BankRequest {
        public let receiverTerminalId: String?
        public let senderAccountId: String?
        public let amount: Double
        public let description: String?
        public let accountId: String

        public typealias Response = Autogen.Responses.UserTransaction

        public init(receiverTerminalId: String? = nil, senderAccountId: String? = nil, amount: Double, description: String? = nil, accountId: String) {
            self.receiverTerminalId = receiverTerminalId
            self.senderAccountId = senderAccountId
            self.amount = amount
            self.description = description
            self.accountId = accountId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/accounts/\(accountId)/transactions"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            if receiverTerminalId != nil {
                dict["receiver_terminal_id"] = receiverTerminalId
            }

            if senderAccountId != nil {
                dict["sender_account_id"] = senderAccountId
            }

            dict["amount"] = amount

            if description != nil {
                dict["description"] = description
            }

            return dict
        }
    }
}
