// DO NOT EDIT: File is generated by code generator.
import APIKit

public extension Autogen.BankAPI.Bank {
    struct CreateBankPay: BankRequest {
        public let privateMoneyId: String
        public let callbackUrl: String
        public let kana: String?
        public let userId: String

        public typealias Response = Autogen.Responses.BankPaySession

        public init(privateMoneyId: String, callbackUrl: String, kana: String? = nil, userId: String) {
            self.privateMoneyId = privateMoneyId
            self.callbackUrl = callbackUrl
            self.kana = kana
            self.userId = userId
        }

        public var method: HTTPMethod {
            return .post
        }

        public var path: String {
            return "/users/\(userId)/banks"
        }

        public var parameters: Any? {
            var dict: [String: Any] = [:]

            dict["private_money_id"] = privateMoneyId

            dict["callback_url"] = callbackUrl

            if kana != nil {
                dict["kana"] = kana
            }

            return dict
        }
    }
}
